name: Update Publications

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 0 1 * *'
  workflow_dispatch:
    
jobs:
  update:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
        
      - name: Run fetch script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: node scripts/fetchPublications.js


      - name: Commit publications.json update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/publications.json
          git diff --cached --quiet || git commit -m "📚 Auto-update publications"
          git push

          
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn deploy
