name: Auto Rename Certificates

on:
  push:
    paths:
      - 'public/img/certificates/**'
      - 'scripts/rename_auto.js'
      - '.github/workflows/rename-certificates.yml'
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧹 Clean up yarn cache (just in case)
        run: |
          yarn cache clean
          rm -rf node_modules

      - name: 📦 Install dependencies using Yarn
        run: yarn install --frozen-lockfile

      - name: 🧪 Confirm @google/genai exists
        run: yarn list --pattern @google/genai

      - name: 🔐 Run rename script with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node scripts/rename_auto.js
