name: Auto Rename Certificates

on:
  push:
    paths:
      - 'public/img/certificates/**'
      - 'scripts/rename_auto.js'
      - '.github/workflows/rename-certificates.yml'
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🧹 Clean yarn cache
        run: yarn cache clean

      - name: 📦 Install dependencies using Yarn
        run: yarn install --frozen-lockfile

      - name: 🧪 Confirm @google/genai is installed
        run: yarn list --pattern @google/genai


      - name: 🔐 Run rename script with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node scripts/rename_auto.js

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn deploy
