name: Auto Rename Certificates

on:
  push:
    paths:
      - 'public/img/certificates/**'
      - 'scripts/rename_auto.js'
      - '.github/workflows/rename-certificates.yml'
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🧹 Clean node_modules and Yarn cache
        run: |
          rm -rf node_modules yarn.lock
          yarn cache clean

      - name: 📦 Reinstall dependencies from scratch
        run: |
          yarn install --verbose

      - name: 🧪 Confirm genai exists
        run: yarn list --pattern @google/genai


      - name: 🔐 Run rename script with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node scripts/rename_auto.js
